### ISSUE TITLE
Firefox Stylus + overlay-scrollbars not working

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/overlay-scrollbars#1]
Hi there.

Ive been using these scrollbars + Stylish addon https://addons.mozilla.org/en-US/firefox/addon/stylish/  with great success.

Recently due to upcoming Firefox 57 I started migrating to Stylus https://addons.mozilla.org/en-US/firefox/addon/styl-us/ and this is utterly ignored.

Would you have any ideas or fixes?

thanks you.

**Comment by silverwind** [comment]
This is pretty much a Stylus issue because it does not support `AGENT_SHEET` yet. I opened https://github.com/openstyles/stylus/issues/188 for of it.

As a workaround, you can paste the CSS into [`userChrome.css`](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes).

**Comment by the-j0k3r** [comment]
That bug was closed, seems userChrome it is and nothing else.

**Comment by the-j0k3r** [comment]
odd, I followed the instructions exactly and restarted Firefox, nothing happened :(

**Comment by silverwind** [comment]
I wasn't aware of it but apparantly styling scrollbars via `userChrome.css` was disabled many years ago (see http://forums.mozillazine.org/viewtopic.php?f=18&t=796805 and https://bugzilla.mozilla.org/show_bug.cgi?id=424184), so I'm afraid it's currently not possible at all in 57+ unless Mozilla adds some API to do so (or allows `userChrome.css` to touch scrollbars).

**Comment by silverwind** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1397345

**Comment by the-j0k3r** [comment]
So when stylish addon dies we have to endure ugly scrollbars, nice, thanks again Mozilla.

thanks silverwind for trying at least ;)

**Comment by the-j0k3r** [comment]
I found this https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Scrollbar, but no idea really.

**Comment by silverwind** [comment]
I don't think that's going to work come 57. What could work is `extensions.legacy.enabled` and the old Stylish extension, but who knows for how long they'll keep support.

**Comment by the-j0k3r** [comment]
I became aware of that setting after the initial discussion. They will probably keep it around for a few releases after, probably to give more developers a chance to transition their legacy addons to web-extensions.
While that may be a stopgap for this problem, it wont resolve it once they turn it off for good because like you noted, there is no support whatsoever for this.

It wont just be this that suffers, but I chose Firefox back then because it was the most customizable and this move will kill that, making it to the users more of the same what other browsers do, since the underlying tech is rarely exposed to regular users, who dont care if they use rust or whatever buzz word they think its cool at the time.

**Comment by PINCHO93** [comment]
Mozilla is slowly but surely kiiling Firefox, hope they notice this in time, and does something about it.

**Comment by kokoko3k** [comment]
Maybe there is a workaround.
You can still hide the current scrollbars with this in userChrome.css:
```
#content browser {
 margin-right: -5px !important;
 overflow-y: scroll;
 overflow-x: hidden;
}
```
And, as far as i know, you can draw NEW scrollbars in the page itself...maybe with an userscript instead of an userstyle... right?

**Comment by silverwind** [comment]
Hiding the scrollbars via overflow and drawing JS scrollbars over that has always been possible, but it's something I'd rather avoid because JS scrollbars can be laggy and are generally a worse user experience than pure CSS ones.

On topic here, there is some movement on standardizing CSS scrollbars, but it's very early:

https://github.com/w3c/csswg-drafts/tree/master/css-scrollbars-1

**Comment by silverwind** [comment]
Firefox 64 now supports these new standardized scrollbar styles. Updated this style to use those. They look pretty similar to the old ones, only issue I found is that there seems to be no way to style the active (clicked) color any more, but it's not a big ssue for me, I rarely click on scrollbars.

**Comment by the-j0k3r** [comment]
Ive a PR up in response to these news, thank you for keeping this thread updated. :) Happy Holidays
